### ISSUE TITLE
if/else

### ISSUE THREAD

**Issue by s0kil** [mgibas/vanilla-dom#1]
Come on now, There is a for loop, but no if statement?

**Comment by mgibas** [comment]
Yeah - `display: none` is way faster than dom manipulation.

**Comment by s0kil** [comment]
Could you please provide an example using `display:none`?

**Comment by mgibas** [comment]
you can use html5 `hidden` attribute (https://www.w3schools.com/tags/att_global_hidden.asp)
```
<div hidden="{{st.hide}}"></div>
```
then just set `true` or `false` on `hide` property and update template.
if you want to support `hidden` attribute in older browsers just add this style:
```
.my-element[hidden] {
  display: none !important
}
```

**Comment by s0kil** [comment]
Thanks!
